---
language: ruby
sudo: required
dist: trusty
cache: bundler
rvm:
  - ruby-2.7.0
  - ruby-3.0.1
install:
  - gem uninstall bundler
  - gem install bundler --version '2.2.29'
  - bundle install
script: "rake"
