---
language: ruby
sudo: required
dist: trusty
cache: bundler
rvm:
  - ruby-2.6.4
  - ruby-2.7.0
  - ruby-3.0.1
install:
  - gem install bundler --version '2.2.29'
  - bundle install
script: "bundle exec rspec spec --exclude-pattern 'cli*'"
